# For help with configuration see https://github.com/rszyma/kanata-tray/blob/main/README.md#configuration
"$schema" = "https://raw.githubusercontent.com/rszyma/kanata-tray/main/doc/config_schema.json"

[general]
allow_concurrent_presets = false
control_server_enable = false
control_server_port = 8100

[defaults]
tcp_port = 5829
autorestart_on_crash = false
kanata_config = '/Users/g3rv4/projects/kanata/kanata.kbd'
kanata_executable = '/usr/local/bin/kanata'

[defaults.hooks]
# Hooks allow running custom commands on specific events (e.g. when starting preset).
# Documentation: https://github.com/rszyma/kanata-tray/blob/main/doc/hooks.md

[defaults.layer_icons]


[presets.main]
autorun = true